version: '3.8'

services:
    back_end:
        image: 62070040/majorbackend
        ports:
            - 3000:3000
    frontend:
        image: 62070040/majorfrontend
        ports:
            - 8080:8080