version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
            - 80:3000
        volumes:
            - ./backend:/usr/src/backend
        restart: unless-stopped
    # frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: ./Dockerfile
    #     ports:
    #         - 80:80
#     database-1.cwqp3zvidlqe.us-east-1.rds.amazonaws.com:
#         image: mysql:8.0.21
#         cap_add:
#             - SYS_NICE
#         ports:
#             - 3366:3306
#         environment:
#             MYSQL_ROOT_PASSWORD: 62070040
#             MYSQL_DATABASE: concert
#             MYSQL_PASSWORD: 62070040
#         volumes:
#             - mysql_db:/mysql
#             - ./mysql-init:/docker-entrypoint-initdb.d
#         command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
# volumes:
#   mysql_db: {}